### ISSUE TITLE
It would be great if you had a discord server for help n support :)

### ISSUE THREAD

**Issue by pinnakkkk** [Neogoma/stardust-SDK#26]

**Comment by loickobesGH** [comment]
Hey @pinnakkkk, 
We've been speaking about it with internally but we're (too) lean for now, covering every continent with online support will have to wait for later this year. 
So for now all we can offer is a direct support from @handrianj, he will get back to you asap! Feel free to shoot him a message directly. 
Hope this helps, thanks for your interest in augmenting the world with StardustSDK!
Best, 
Loic
