### ISSUE TITLE
[BUG] Stardust App - Stops uploading images after receiving message to slow down. 

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#27]
When creating or retraining a map using the Stardust app, upload will stop after receiving the warning to move more slowly. 

**To Reproduce**
1. Create a new map
2. Retrain the map
3. move your phone quickly to get the move more slowly error
4. No more images in the queue will upload

**Comment by sam1am** [comment]
I have found that this also happens even if you have not received the move slowly warning. 

Phone is Samsung Galaxy S21 on latest update.

**Comment by handrianj** [comment]
Just wondering, does the issue happen on wifi, 4g or both?

**Comment by sam1am** [comment]
Both WiFi and 5G.  

Here are some videos of my testing showing the issue: https://photos.app.goo.gl/M53T4rGJRcinRJvL6  

I am having trouble making it happen consistently.

**Comment by sam1am** [comment]
I have a particular map that I can relocate, but it won't add a single image no matter what I try.  

It doesn't seem like a connection issue because I am able to generate and update other maps normally.  

![image](https://user-images.githubusercontent.com/127555/126881493-35146bd6-cce1-489f-ac9c-c718d367f620.png)

One map ID I'm having this problem with is 60fb508247e03.

**Comment by handrianj** [comment]
Thanks for all this info Sam, we'll dig into it altho this issue will take a little bit time to solve because we have difficulties reproducing it on our side!

**Comment by handrianj** [comment]
Long shot but can you check if it still happens with [this](https://github.com/Neogoma/stardust-SDK/releases/tag/0.62a)?
