### ISSUE TITLE
Add timeout to server call

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#28]
When asking the server to localize, if it doesn't respond (either due do a client network error or the server being unavailable) it will hang forever. 

It would be nice if there was a timeout in the download method and some kind of informative error response.

**Comment by handrianj** [comment]
So... Technically we already have a failsafe in case of timeout, but we don't have any mechanism to deal with very long uploads (we send only one frame on relocation but it's possible that network conditions make that upload very slow...).

We can provide a progress update or a manual timeout (if request takes more than XXX second consider it as a failure). Let us know which approach you would find more useful in your case

**Comment by sam1am** [comment]
I think a manual timeout would do the trick. 

It would be great to have progress update but not strictly necessary I think.

**Comment by handrianj** [comment]
We set up a timeout call [here](https://github.com/Neogoma/stardust-SDK/releases/tag/0.62a).
