### ISSUE TITLE
Unity "Import Point Cloud" imports previously set point cloud. 

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#29]
1. Download a point cloud into Unity
2. Download a different point cloud into Unity

The second point cloud will download a duplicate of the first instead of whatever you set it to.  

Workaround: Restarting Unity seems to fix this issue.

**Comment by sam1am** [comment]
I have found that it will even pull in a map that has been deleted. So it must be pulling from local cache? (assuming deleted maps are actually deleted).

**Comment by handrianj** [comment]
> I have found that it will even pull in a map that has been deleted. So it must be pulling from local cache? (assuming deleted maps are actually deleted).

That should be corrected very soon.

> The second point cloud will download a duplicate of the first instead of whatever you set it to.

We'll correct it in 0.62

**Comment by handrianj** [comment]
Should be corrected [here](https://github.com/Neogoma/stardust-SDK/releases/tag/0.62a).
