### ISSUE TITLE
Upload point cloud from other apps

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#31]
I am finding it somewhat difficult to map reliably using the Stardust app. The resulting point clouds are far less dense (and more difficult to work off of) than what I would get by scanning with another app. 

However, many free and paid solutions exist to make highly accurate 3d scans and point clouds in any common format.  

I understand this is not how the tech is currently designed to work, but it would be amazing at some point to leverage some of the existing tools that provide a superior scan experience.   

My current workaround is to make a 3d scan with another app, then align it to the point cloud so I can use it as a better reference. But in practice I've had some difficulty doing this perfectly.

**Comment by handrianj** [comment]
Technically if you can properly identify the 0,0,0 of your 3D scan it works. You only need to match the 0,0,0 of your scan with the 0,0,0 of your prefab in unity. You don't even need to download the generated point cloud.

**Comment by sam1am** [comment]
The main problem is that I am finding it difficult to create good quality point clouds using the API. Areas are coming back disjointed, with parts out of scale, etc. It can take an hour for a point cloud to generate before you know that the data is messed up, and then you have to start all over. 

But I can generate good quality point clouds using local tools and curate an image set that will produce good results very quickly.  

The other day I was showing a demo as party of a gallery project. The day of the show, the gallery cleaned everything out and moved furniture, etc. I was not able to update the existing scan at all. It would tell me I was moving too quickly even when holding still and would not upload images. So I tried a few times to create new scans of the area from scratch and they kept coming out really messed up.

**Comment by handrianj** [comment]
> It can take an hour for a point cloud to generate before you know that the data is messed up, and then you have to start all over.

I think that point goes all the way back to [this issue](https://github.com/Neogoma/stardust-SDK/issues/30). When we will release the update to limit the cases of bad data your point clouds should be better positioned.
 If the mapping is messed up, the point cloud is messed up and I suspect it might be the case in your situation. Do you allow us to check the datas to check the issue on our side on this specific map ? If so please send us the UUID of the maps by mail (heri[at]neogoma[dot]com).
 
> I understand this is not how the tech is currently designed to work, but it would be amazing at some point to leverage some of the existing tools that provide a superior scan experience.

I think on the unity editor side we could change the current import to not only import the point cloud but also the mapping path (a little bit like the navigation view in the Online editor) so it will be easier to position/scale an external point cloud without waiting for the generation on our side.

**Comment by sam1am** [comment]
> I think on the unity editor side we could change the current import to not only import the point cloud but also the mapping path (a little bit like the navigation view in the Online editor) so it will be easier to position/scale an external point cloud without waiting for the generation on our side.

That's a good idea. I also followed your suggestion in another thread to place objects as I scan, which accomplishes the same thing. Scan path would be great, though.

**Comment by handrianj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update point cloud on map update](https://trello.com/c/4Qt48EXL/5-update-point-cloud-on-map-update)
