### ISSUE TITLE
How to do edit scripts it gives me warning "Unable to open Assets/Neogoma/hobodream-sdk/Plugins/Hobodream.dll: Check external application preferences"

### ISSUE THREAD

**Issue by pinnakkkk** [Neogoma/stardust-SDK#32]
my external tools is set to VS code yet it doesnt open, tried both VS studio n VS code editor.

**Comment by pinnakkkk** [comment]
my external tools is set to VS code yet it doesnt open, tried both studio n code editor.

**Comment by handrianj** [comment]
Are you using your own project or one of the samples?

**Comment by pinnakkkk** [comment]
Sample

**Comment by pinnakkkk** [comment]
> Are you using your own project or one of the samples? 

Samples I cloned it from GitHub

**Comment by sam1am** [comment]
It looks like you are trying to edit a .dll file, which isn't something you'd normally do in VS code. You are probably looking for the Scripts/ folder. The scripts you want to look at end in .cs file extension.

**Comment by pinnakkkk** [comment]
> It looks like you are trying to edit a .dll file, which isn't something you'd normally do in VS code (it is binary computer code). You are probably looking for the Scripts/ folder. The scripts you want to look at end in .cs file extension. 


Yes, but I was open a script file for a button.

**Comment by pinnakkkk** [comment]
also I created a new script and tried to open it but same warning ;(

**Comment by handrianj** [comment]
You can safely ignore the warning, you can still build. It has no impact.
