### ISSUE TITLE
On updating a map, also update point cloud

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#33]
I am not seeing data from updates to maps being re-generated into the point cloud. This would be helpful to make sure everything is lining up and looking good, and to be able to accurately add on to areas.

**Comment by handrianj** [comment]
The feature is actually planned in the roadmap! No release date yet because it heavily depends on relocation and the stability of data upload.

**Comment by handrianj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mapping batch](https://trello.com/c/Zqzw0xa5/4-mapping-batch)

**Comment by handrianj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update point cloud on map update](https://trello.com/c/4Qt48EXL/5-update-point-cloud-on-map-update)
