### ISSUE TITLE
Relocation Scene doesn't work

### ISSUE THREAD

**Issue by pinnakkkk** [Neogoma/stardust-SDK#34]
I wanted 2 different apps like mapping & relocation so i build both scene as diff app, the Mapper Scene works but the Relocation-updater doesn't work like it gives me dropdown, I select the map but then it doesn't show downloading the map or locate me btn.
PS. I haven't deleted any prefab or change the script.  Using demo repository from stardust. and the API key is correct. I've build relocation & updater.

**Comment by handrianj** [comment]
Are you listening to the event of the dropbox properly? I suspect that nothing notifies when the selection is done.

**Comment by pinnakkkk** [comment]
![image](https://user-images.githubusercontent.com/52191876/127092091-6f45f0ee-19bd-469f-892f-cb474b4f8e15.png)


> Are you listening to the event of the dropbox properly? I suspect that nothing is notified when the selection is done.

![image](https://user-images.githubusercontent.com/52191876/127092121-4c9611ea-a91a-4804-8d12-194fd0b04b30.png)

I guess so that is the issue, how do i do it? cause I havent changed anything so im not sure what i need to change
here is the img of mapSelectionDropDown Prefab
![image](https://user-images.githubusercontent.com/52191876/127092283-9fdf280b-d51e-4dd5-9993-5839a4022c51.png)

**Comment by handrianj** [comment]
Can you show me the version of Stardust SDK is used ? I remember I updated that issue a few weeks ago

**Comment by pinnakkkk** [comment]
> Can you show me the version of Stardust SDK is used ? I remember I resolved that issue a few weeks ago

0.61 I cloned it 2 days back

**Comment by handrianj** [comment]
Does the relocation scene work ?

**Comment by pinnakkkk** [comment]
> Does the relocation scene work ?

Yes if the whole project is complied in one app then yes it works

**Comment by handrianj** [comment]
Did you assign the method `OnMapDownloaded ` as a listener of `onValueChanged` on the dropdown?

**Comment by pinnakkkk** [comment]
> stener

Sorry I dont exactly on what u mean.
this is the RelocationDemo.cs class on AR session
![image](https://user-images.githubusercontent.com/52191876/127097910-6cdd4048-98fb-4d4a-aad5-0a43df0da3b9.png)

**Comment by pinnakkkk** [comment]
> Did you assign the method `OnMapDownloaded ` as a listener of `onValueChanged` on the dropdown? This is done in the [RelocationDemo.cs](https://github.com/Neogoma/stardust-SDK/blob/master/Assets/Script/Navigator/RelocationDemo.cs) class

like on the "dropdown" prefab "onvaluechanged"  i attached RelocationDemo.cs on it but there was no such function where as that script has a function. 

and on the AR Session attached Relocation script if i add the mapSelectionDropDown and go to dropdown>then also there is no such function.

**Comment by handrianj** [comment]
> like on the "dropdown" prefab "onvaluechanged" i attached RelocationDemo.cs on it but there was no such function where as that script has a function.

In the example, this is done programatically. I think you will need to debug what happens if you select the map (you can just debug log to know if you enter on the `OnMapSelected` method.

If you want a more simple example for relocating you can check [this tutorial](https://neogoma.github.io/stardust-SDK-doc/#/developer/0_1_empty_project).

**Comment by pinnakkkk** [comment]
> method



> > like on the "dropdown" prefab "onvaluechanged" i attached RelocationDemo.cs on it but there was no such function where as that script has a function.
> 
> In the example, this is done programatically (you won't be able to assign them from inspector because everything is private). I think you will need to debug what happens if you select the map (you can just debug log to know if you enter on the `OnMapSelected` method).
> 
> Otherwise, if you want a more simple example for relocating you can check [this tutorial](https://neogoma.github.io/stardust-SDK-doc/#/developer/0_1_empty_project).

Yes it properly sents the int val to the "OnMapSelected" but before that only console throws an error that Map UUID can't be null

```private void OnMapSelected(int val)
        {
            selectedSession = indexToSession[val];
            Debug.Log(val);
            if (selectedSession != null)
            {
                mapSelectionDropDown.gameObject.SetActive(false);
                relocationManager.GetDataForMap(selectedSession);
                sessionName.text = selectedSession.name;    
                Debug.Log(val);

            }            
        }    ```
        
![image](https://user-images.githubusercontent.com/52191876/127101086-81e8ec12-a8e8-4f8e-9528-37b11d24b849.png)

**Comment by handrianj** [comment]
Yup our bad it was probably an error on our side: can you check if [this update](https://github.com/Neogoma/stardust-SDK/releases/tag/0.611a) solves your probelm

**Comment by pinnakkkk** [comment]
> It was a bug on our side: can you check if [this update](https://github.com/Neogoma/stardust-SDK/releases/tag/0.611a) solves your problem?

should I just import it as a Unity package?

**Comment by handrianj** [comment]
Yes

**Comment by pinnakkkk** [comment]
> Yes, you just import it in your project and you replace all the existing assets (normally only the Stardust.dll should be updated).

Yup it fixed the issue.
