### ISSUE TITLE
What is the best settings for Occlusion manger for android?

### ISSUE THREAD

**Issue by pinnakkkk** [Neogoma/stardust-SDK#36]
The pathway to the destination can be seen thru the walls the Occlusion doesn't work.
I'm using Redmi K20 API 30

**Comment by handrianj** [comment]
Are you using the standard ARFoundation occlusion manager? This function is relying on the ARCore depth API which is not available for all phones. Our SDK doesn't manage that.

A reliable workaround would be to create the occlusion with shaders yourself using stencil shaders.

**Comment by pinnakkkk** [comment]
> Are you using the standard ARFoundation occlusion manager? This function is relying on the ARCore depth API which is not available for all phones so make sure yours can run occlusion first. Our SDK doesn't manage that.
> 
> A reliable workaround would be to create the occlusion with shaders yourself using stencil shaders. Then you can use your own model with the custom stencil shader you wrote by replacing our standard Arrow with your own prefab.
> 
> I will close the issue since it's not SDK related

okay I wanted to do that with custom arrow obj but everytime the 3d object is placed 90deg even if the prefab is at 180deg so whats wrong there then?

**Comment by handrianj** [comment]
> also cant see the code for placing the arrows its in dll file.

Yup for now the code is our own as many other classes but we will give the possibility for developers to override it later.

>  the 3d object is placed 90deg even if the prefab is at 180deg

- Create an empty object
- Put the arrow you want as child of the empty object
- Try to rotate the arrow in a way that it will appear in the correct rotation when it is instantiated

If you inspect the Arrow prefab in the SDK this is exactly what we're doing.

**Comment by pinnakkkk** [comment]
> > also cant see the code for placing the arrows its in dll file.
> 
> Yup for now the code is our own as many other classes but we will give the possibility for developers to override it later.
> 
> > the 3d object is placed 90deg even if the prefab is at 180deg
> 
> * Create an empty object
> * Put the arrow you want as child of the empty object
> * Try to rotate the arrow in a way that it will appear in the correct rotation when it is instantiated
> 
> If you inspect the Arrow prefab in the SDK this is exactly what we're doing.

Thanks! it worked but the arrows aren't constant like they are far apart rather than close and make an array, could it be bad mapping?

**Comment by handrianj** [comment]
> Thanks! it worked but the arrows aren't constant like they are far apart rather than close and make an array, could it be bad mapping?

The navigation path is calculated based on your mapping path (we do this so the user doesn't have to manually define path but instead everything that has been mapped is navigable).

If you want to customize your rendering based on the path then you will have to wait 0.62 where we will allow you to create your own rendering script

**Comment by handrianj** [comment]
We just release 0.62 that allows you to customize your own navigation path.

**Comment by pinnakkkk** [comment]
> We just release 0.62 that allows you to customize your own navigation path.

Is there any documentation to it?

**Comment by handrianj** [comment]
> Is there any documentation to it?
I'm writing it XD

**Comment by handrianj** [comment]
> > We just release 0.62 that allows you to customize your own navigation path.
> 
> Is there any documentation to it?

The doc is available [here](https://neogoma.github.io/stardust-SDK-doc/#/developer/2_1_custom_navigation_path). It's not big because most of the code in the classes will have to be written by you as your custom rendering.

**Comment by pinnakkkk** [comment]
> > > We just release 0.62 that allows you to customize your own navigation path.
> > 
> > Is there any documentation to it?
> 
> The doc is available [here](https://neogoma.github.io/stardust-SDK-doc/#/developer/2_1_custom_navigation_path). It's not big because most of the code in the classes will have to be written by you as your custom rendering.

Thank you so much! I read the docs so  in DisplayPath() I just need to instantiate the prefab? And in ClearPath() destroy the instantiated prefabs? 
Sorry if it's a very basic question, I'm still a newbie🥲 also if u can update some kind of example in docs like u did in setup UI script, it would be helpful!!

**Comment by pinnakkkk** [comment]
> > > We just release 0.62 that allows you to customize your own navigation path.
> > 
> > 
> > Is there any documentation to it?
> 
> The doc is available [here](https://neogoma.github.io/stardust-SDK-doc/#/developer/2_1_custom_navigation_path). It's not big because most of the code in the classes will have to be written by you as your custom rendering.

As per my rookie knowledge i need to  get the list from allnavigationpoints in a loop and create an instance with allnaigationpoints coords and render them? if not then i absolutely no idea how to make one so i really need some kindof example for what code for code written inside the methods ;(

**Comment by handrianj** [comment]
> i need to get the list from allnavigationpoints in a loop and create an instance with allnavigationpoints coords and render them

Yes but we don't guarantee that the points are always same distance from each other so you will MAYBE have to make some calculations.

> if yes then how do i req for x, z position? 

The positions are provided by the interface IOctreeCoordnateObject. You just get the coordnates and then you decide how do you want to display your object from it.
