### ISSUE TITLE
[BUG] Can not relocate

### ISSUE THREAD

**Issue by Dweeh** [Neogoma/stardust-SDK#44]
**Describe the bug**

When Build and Run - nothing happens when I press the button to locate.

I tried on several different scenes and projects - including starting from the Stardust SDK project AND the tutorial-simple-relocation-main project.
I just can not get it to work.

I checked and triple checked that everything is connected as it should 
- but with the tutorial-simple-relocation-main project - that risk should be minimized.
I am just using the script from the tutorial-simple-relocation on the website - and did not change the one on the downloaded tutorial project.

Been on this for days now.
Would be nice to know if you can reproduce the problem.

**Unity version**
Unity: [e.g. Unity 2021.1.16f1 Personal]
ARFoundation: [e.g. ARFoundation 4.1.7]

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6]

**Sessions information**
Session ID  - Tried different ones.
New with first mapping and also old updated ones

**Comment by handrianj** [comment]
Sorry for the inconvenience we're currently migrating to another cloud provider so it might be related to that, what do your logs says about it ?

**Comment by Dweeh** [comment]
But the app worked fine...

I will check the log again when the migration is done and get back to you.

**Comment by handrianj** [comment]
The migration is done now and mapping/relocation should work now.

**Comment by Dweeh** [comment]
I get a message that the server version is 0.7 - but the package to download here is still 0.65.
Will the package be updated or can I assume that the old package still works ok?

**Comment by handrianj** [comment]
The old package is still compatible. We are still waiting for store reviews before officially releasing the package

**Comment by Dweeh** [comment]
I managed to relocate using the tutorial-simple-relocation-main project.
So it works now  :)

**Comment by handrianj** [comment]
Good! We just released 0.7 [here](https://github.com/Neogoma/stardust-SDK/releases/tag/0.7).

We also updated the documentation for the simple relocation [here](https://neogoma.github.io/stardust-SDK-doc/#/developer/0_1_empty_project).
