### ISSUE TITLE
[BUG] Can not move slow enough to be able to map with the app from Play Store

### ISSUE THREAD

**Issue by Dweeh** [Neogoma/stardust-SDK#47]
**Describe the bug**

When using the app to map - I get the warning "You are moving to fast" even if I hardly move at all.
Right after that - the "Drifting detected, capture stopped" are triggered.

It seems impossible to map right now.
Tried on two different locations outdoors and both along the side of a building and along the street - with the same result.

**To Reproduce**
1. Open the Stardust app downloaded from Play Store 
2. Create a new scene
3. Start the mapping
4. Try to finish a whole mapping

**Comment by handrianj** [comment]
Hi, thanks for your feedback. Unfortunately, not all android phones are equal and some might be prone to more drifting than others. We're still working on a way to compensate for the drifting but most of the fixes for this issue will be some UX to prevent users from creating maps with the wrong data.

For now, we suggest that after opening the scan scene you walk around a little bit (before starting to capture datas). This will allow your phone to stabilize the SLAM.
