### ISSUE TITLE
[How to] In local building process, difficulty in loading contents

### ISSUE THREAD

**Issue by polarecreater** [Neogoma/stardust-SDK#50]
Hi Using unity, I am making ar application following this link. [https://neogoma.github.io/stardust-SDK-doc/#/developer/1_2_point_cloud_import?id=import-the-point-cloud](url)

But if I build the scene, then nothing happened in my application.
I want to find the reason, so I take some actions for the errors happened, like this picture.
![image](https://user-images.githubusercontent.com/34772283/141080457-53e214ef-c055-4f0b-a380-332e846324ee.png)

But it does not make any change on my application, so I wonder how the contents loading.

Especially, _**Remove (or disable) both the point cloud and the Content object in YOUR scene**_ this sentence of your document makes me confuse. 

If the map id is disabled on the scene, how can it recognize the map in local application which I made (which is not stardust application.)

And I also have another question. 
I want to make point cloud of my seat, so I filmed the video through stardust app at one position but moving camera around. This is the result.
![image](https://user-images.githubusercontent.com/34772283/141081721-bdb54cbf-cfad-41be-af4e-d7ae62fd7469.png)
I think it is not working properly, so I wonder if the movement is necessary.

Thank you for reading this.
I will wait for the answer.

**Comment by handrianj** [comment]
Hi, thanks for your feedback! Do you have any logs?

> Especially, Remove (or disable) both the point cloud and the Content object in YOUR scene this sentence of your document makes me confused.

The reason why we tell the users to disable the content before the build is that otherwise, it will appear when the AR scene starts. The **first time** a relocation happens, the whole Content object will be instantiated again whether it is present in the scene or not.

>  I think it is not working properly, so I wonder if the movement is necessary.

In order to generate a good point cloud, we wrote the [mapping guidelines](https://neogoma.github.io/stardust-SDK-doc/#/mapping_strategy) to get optimal results.

**Comment by polarecreater** [comment]
I will retry following mapping guidelines, thank you.

I have another questions,

1. How can I recognize relocation happened? I worried because I build the app on my own, not using stardust app.
2. I think you guys make point cloud using phone lidar sensor or ai using filmed pictures. 
    I have **.las file(and binary file** which is converted .las file) which have very good point cloud of specific area. 
    I want to make AR contents on it, like stardust sdk.
   Do you have any way to upload .las file and make ar contents on it?

**Comment by handrianj** [comment]
> How can I recognize relocation happened? I worried because I build the app on my own, not using stardust app.

If you are using your own app you will need to write code to properly intrpret the results of relocation. We provided a guide to all the events from MapRelocationManager [here](https://neogoma.github.io/stardust-SDK-doc/#/developer/comp_map_relocation_manager?id=events). 

You can listen to the **onPositionFound** and **onPositionNotFound** events to know if your relocation was sucessfull or not.

>  Do you have any way to upload .las file and make ar contents on it?

We don't have any way to import point cloud from other apps. You can write your own parser for .las file in unity and import it in your scene manually.
