### ISSUE TITLE
[How to] use the AutoLogin feature

### ISSUE THREAD

**Issue by jcheckett25** [Neogoma/stardust-SDK#6]
Description: I opened the scene "SelectionScene" in Unity. I click on "StardustComponents" in the hierarchy, and go to "API Auto Login (Script) section in the Inspector to fill in my credentials. When I build this app to my developer phone (Samsung Galaxy Note 20 Ultra) I get "Login Failed, check credentials."

I've registered hours prior to actually using Stardust-SDK, and received an email stating that my account was activated. I also tried accessing https://stardust.neogoma.com/api/login, but I receive an error.

**Comment by handrianj** [comment]
Hi, we released an update yesterday that discarded all the autologin components and replaced it with an API key, you should either update with the [latest release](https://github.com/Neogoma/stardust-SDK/releases/tag/v0.2-alpha) and follow the [upgrade guide](https://neogoma.github.io/stardust-SDK/#/upgrade_guide?id=upgrade-from-01x-to-02) or re-clone the project.
