### ISSUE TITLE
[BUG] Mapping upside-down

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#62]
**Describe the bug**
Point Cloud comes out upside down and wonky

**To Reproduce**
1. ?? I am attempting to scan a large water tower. It is too large to go all the way around before I run out of photos. 

**Screenshots**
![image](https://user-images.githubusercontent.com/127555/157604550-85012f1e-22ef-460f-8f1c-8d18f52888b8.png)

**Unity version**
Unity 2021.3.13f

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21

**Sessions information**
Map IDs: 
62292e5dc1724
62292cea4492d

**Comment by MrRobat0** [comment]
Hey @sam1am,

We're currently figuring out the issue in our backend.
This issue usually happens when mapping with the phone in landscape or any different orientation other than completely vertical. But it doesnt seem to be your case. 

Regarding the size of the scan, your're right it is a bit too large for the ammount of pictures you have. Have you tried scanning a smaller environment where you can walk around it ?

Thanks for pointing it out.

**Comment by sam1am** [comment]
Which devices do you use for testing? Would an iPhone be more reliable?

**Comment by MrRobat0** [comment]
We use a range of devices to test throughout the team, I use both a pixel 3XL and iphone 12 and the camera quality and picture resolution of the iphone is just a lot smoother. 

Stable pictures with higher quality and less blur will have better results.

**Comment by sam1am** [comment]
Are other sensors used at all when looking for a match? Like gps and compass for example. 

Also, is it intended that the end user will stand in the exact same starting location as you? Or anywhere within the mapped area roughly along the camera path?

**Comment by MrRobat0** [comment]
Hey Sam, It's fully visual positioning. Only data used for relocation are the pictures taken during the mapping process.

Given a good map the user is able to relocate anywhere, as long as it has been mapped reliably.

Things to avoid:

- Blurry pictures while mapping or relocating
- Not enough pictures uploaded while mapping
- Not enough updates
- Trying to relocate in a place that has not been mapped.
- Drastically different lighting conditions, without updating the map.
