### ISSUE TITLE
[BUG] Cannot update scan

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#63]
**Describe the bug**
When attempting to map a large open area with multiple scans, subsequent scans do not take photos or upload to the server. 

**To Reproduce**
1. Build project from source
2. Follow instrictions for mapping a large open area
![image](https://user-images.githubusercontent.com/127555/157814184-62e0200c-a160-4bd7-86af-b5152a7e237d.png)
3. Second scan will not complete. 

**Expected behavior**
Continue taking pictures and add on to the model on the server. 

**Screenshots**
Behavior can be seen in this video: https://photos.app.goo.gl/c84svfSnkpRF5JRN9

**Unity version**
Unity: [e.g. Unity 2021.3.13f]

**Smartphone (please complete the following information):**
 - Device: Galaxy S21

**Comment by MrRobat0** [comment]
Hey Sam, 

Thanks for pointing that issue, we have just updated the repo and a fix should be ready.
The repo was setup wrong making it impossible to update.

Should be fixed now !
