### ISSUE TITLE
[BUG] Changes made on cloud do not save

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#67]
Changed made on the cloud interface do not seem to save. Items will save, but you can't change their location or size reliably. 

Edge/Chrome on Mac OS. 

Here is a screen capture showing the issue. 

https://photos.app.goo.gl/3q6NJ21YSpvRC1SS6

**Comment by handrianj** [comment]
Hi Sam! Thanks for raising the issue, the problem has now been fixed. You can check and let us know if we can close this issue?

**Comment by sam1am** [comment]
Yes it looks like it is working now, thanks.
