### ISSUE TITLE
Add events for successful relocation to example apps

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#68]
Maybe I am misunderstanding something about how to use this, but I think it would be helpful to have an event in the Map Relocation Manager for "On Position Found Success()"  

<img width="374" alt="Screen Shot 2022-03-13 at 7 45 38 PM" src="https://user-images.githubusercontent.com/127555/158090906-838a26ed-c4ac-473b-96ae-55d84e4f30f4.png">

**Comment by handrianj** [comment]
Hi Sam, actually since we implemented custom unity events they won't appear in the inspector. We're going to expose simple unity events for next release.

**Comment by handrianj** [comment]
Done in 0.902 update
