### ISSUE TITLE
[BUG] 500 Server error when displaying maps

### ISSUE THREAD

**Issue by DoritoDog** [Neogoma/stardust-SDK#73]
**Describe the bug**
Visiting the [maps list](https://stardust.neogoma.com/map_list) results in a 500 Server Error, no maps are displayed.

**To Reproduce**
1. Create a map in the mobile app built in Unity
2. Choose edit map in the browser
3. Exit both and then maps cannot be displayed in the browser

**Expected behavior**
A list of the maps.

**Unity version**
Unity 2020.3.33f1

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Lite

**Browser (if the issue is about navigator or dashboard):**
 - Browser: Chrome

**Comment by handrianj** [comment]
Thanks for reporting,

Can you try again now? We put a fix online and we'd like your feedback

**Comment by DoritoDog** [comment]
Thank you, it's working now.

**Comment by 7osssam** [comment]
This error is still happening when I try to delete any map

**Comment by handrianj** [comment]
> This error is still happening when I try to delete any map

Can you try again, we did a quick migration to AWS this morning and now everything should work as expected
