### ISSUE TITLE
Point Cloud is not completely loaded

### ISSUE THREAD

**Issue by 7osssam** [Neogoma/stardust-SDK#74]
**Describe the bug**
The point cloud is not completely loaded in the web editor and the status of the Relocation and Point cloud is **Ready** should i give it more time or is it a problem? 

**Screenshots**
![image](https://user-images.githubusercontent.com/46269045/174479899-e4c3f046-284b-4915-991e-435b4eed50c2.png)
![image](https://user-images.githubusercontent.com/46269045/174480369-e20c667e-e02f-47b6-8830-a91fbdeda95b.png)

**Smartphone:**
 - Device: iPhone 12 pro max 
 - Version iOS 15.5

**Browser :**
 - Browser: Firefox
 - Version 101.0.1

**Sessions information**
Map_id 62aeef2882025

**Comment by loickobesGH** [comment]
Hi Hossan, 
Our current SFM pipeline might break when 2 or more pictures are disconnected. This can come from sharp turns, blurry pictures, but sometimes also from the lack of features in the physical environments, making matching impossible. 
We are working on a completely new pipeline to overcome those classic computer vision issues. Further on the road map, we'll also offer map stitching and point cloud generation from map update, but for now you'll have to work around it by doing an almost perfect first mapping (updates are only increasing relocation robustness, there's aren't used for 3d reconstruction). You can also use the analyzer to see where in your mapping path (which pictures) might have caused that issue.
