### ISSUE TITLE
[BUG] Importing Point Cloud in Unity not working

### ISSUE THREAD

**Issue by timse1993** [Neogoma/stardust-SDK#76]
I tried to import a point cloud into Unity using the Map ID as described in the docs: https://doc.neogoma.com/#/developer/1_2_point_cloud_import

When I click "Import into editor" nothing happens at all. After one or two seconds I am just back in the editor. No point cloud added, no error or warning in the console. I did set up my dev token and tried different Unity Versions, including the one the repo was created with. I also tried setting up a new scene with the stardust SDK instead of using the sample scenes but same result.

1. Open scene "Relocate-Update"
2. Go to Stardust SDK -> Import point cloud -> Enter Map ID and click import into editor
3. See incoherent behavior

**Expected behavior**
Point cloud gets added to the scene with die Map ID as name of the gameobject.

**Screenshots**

**Unity version**
Unity: [e.g. Unity 2021.3.1f1]
ARFoundation: [e.g. ARFoundation 4.2.6]

**Smartphone (please complete the following information):**

**Browser (if the issue is about navigator or dashboard):**
 - Browser: [e.g. Chrome/Opera...]

**Sessions information**
Session ID [e.g. 1]
First mapping or update

**Additional context**

**Comment by handrianj** [comment]
Hi! Thanks for reporting!

I just tried the function and I can't manage to reproduce the bug on our side. 

1. Did you fill the API Key in the StardustComponents gameobject ?
2. Can you provide us with the Session ID of your Map ? (the issue might be related to something on your map)

**Comment by timse1993** [comment]
Hi, thanks for the quick reply!

1. Yes, I did fill the API Key. I also tried generating a new one in my Account Settings and use that one.
2. Sure, the Map ID is 6332d9caccb08. I generated this one with an iPhone and after that I created a second map with a Samsung device. But that got the same result.

Btw, I am working on Mac. But I also have a windows PC if this might cause the issue.

**Comment by timse1993** [comment]
I just downloaded and opened the Unity Project again and I got 24 errors. 23 of them say that image files could not be read.
For example: "...Assets/Textures/star.png: File could not be read"
The last error is the same with fbx: "ImportFBX Errors: Couldn't read file .../Assets/Prefabs/target.fbx"

I can clear the errors but maybe the point cloud issue has something to do with that

**Comment by handrianj** [comment]
Can you try again now? It should be working

**Comment by handrianj** [comment]
> I just downloaded and opened the Unity Project again and I got 24 errors. 23 of them say that image files could not be read.

The project has been configured to use GIT-LFS so you need to clone the project and now download it otherwise the graphics assets will not be downloaded.

**Comment by timse1993** [comment]
I tried again and it works! I am seeing the point cloud in the unity editor now. I also cloned the repo instead of downloading the files and the other errors are gone as well. 
Thanks for the great support, looking forward to testing out Stardust!

One last question: Did I do something wrong when scanning the map? Just want to know for future scans or if the problem might appear again

**Comment by handrianj** [comment]
> One last question: Did I do something wrong when scanning the map? Just want to know for future scans or if the problem might appear again

Nothing wrong on your side, it was mostly our own end issue. As long as you follow the instructions in the documentation all should be fine! Just walk slowly to avoid drifting!
