### ISSUE TITLE
Map Creation not Working

### ISSUE THREAD

**Issue by MinasKatsiokalis** [Neogoma/stardust-SDK#85]
I clone the repo and built the project as is. (4 Scenes)
I have set my key.
When I launch the app and press  "Create New Map", I fill in the name and then nothing.
In the online database, I see my "map's name" but no data.

**Unity version**
Unity 2022.2.12
ARFoundation: 5.0.4

 - Device: Xiaomi Mi 8

**Additional context**
When I see the logs there is this error showing below
![image](https://github.com/Neogoma/stardust-SDK/assets/9119948/db2aa6e4-2f5f-45c4-8ad8-babff37a6ad5)

**Comment by handrianj** [comment]
Fixed, there was a missing reference in scene
