### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pradeepiitian** [Neogoma/stardust-SDK#89]
**Describe the bug**

**To Reproduce**
1. Open scene [Scene name]
2. Do '...'
3. See incoherent behavior

**Expected behavior**

**Screenshots**

**Unity version**
Unity: [e.g. Unity 2019.4.8f1]
ARFoundation: [e.g. ARFoundation 4.0.8]

**Smartphone (please complete the following information):**

**Browser (if the issue is about navigator or dashboard):**
 - Browser: [e.g. Chrome/Opera...]

**Sessions information**
Session ID [e.g. 1]
First mapping or update

**Additional context**

Not showing any option to downlaod the 3d map in action tab to use in the unity.

**Comment by handrianj** [comment]
We can't reproduce the bug on our end, can you please give more details?

**Comment by handrianj** [comment]
Mesh download is only available for paid users. You can still use the point cloud in the unity editor
