### ISSUE TITLE
error in TargetCreationManager.cs

### ISSUE THREAD

**Issue by VishalS4646** [Neogoma/stardust-SDK#90]
Assets\Script\Exporter\TargetCreationManager.cs(73,77): error CS1061: 'CoordinateSystem' does not contain a definition for 'ConvertFromUnityToMapCoordnate' and no accessible extension method 'ConvertFromUnityToMapCoordnate' accepting a first argument of type 'CoordinateSystem' could be found (are you missing a using directive or an assembly reference?)

**Comment by handrianj** [comment]
Thanks for letting us know about the problem we're going to release a new version soon that will correct this issue

**Comment by handrianj** [comment]
The project has been updated and the error has been solved
