### ISSUE TITLE
Assets\Neogoma\stardust-sdk\Scripts\LocalContentRelocation.cs(10,67): error CS0103: The name 'PositionFound' does not exist in the current context[BUG]

### ISSUE THREAD

**Issue by kanupriyaanand** [Neogoma/stardust-SDK#93]
Assets\Neogoma\stardust-sdk\Scripts\LocalContentRelocation.cs(10,67): error CS0103: The name 'PositionFound' does not exist in the current context
getting the above error when following the documentation and creating a content relocation script

**Comment by handrianj** [comment]
Hi, thanks for notifying us for the mistake

We just added a function in the documentation matching the signature:

```
private void PositionFound(RelocationResults results, CoordinateSystem coordinates)
    {
        Debug.Log("POSITION FOUND");
        Handheld.Vibrate();
    }
```
